### ISSUE TITLE
[詢問] 能否新增個人作品？

### ISSUE THREAD

**Issue by kevinbird61** [hueitan/made-in-taiwan#12]
想請問能否加入自己的小作品：

# Node.js (javascript)

:star2: | Name | Description | 🌍
--- | --- | --- | ---
31 | [docogen](https://github.com/toolbuddy/docoGen) | 從文件格式（json,md）轉換成 LaTeX 格式的 pdf 做輸出 ([簡易說明](https://slides.com/kevinbird61/docogen#/)) | [:arrow_upper_right:](https://github.com/toolbuddy/docoGen/wiki), [demo](https://github.com/toolbuddy/docoGen/blob/master/test/dest/docogen-latex.pdf),[npm package](https://www.npmjs.com/package/docogen)
6 | [@yungshenglu](https://github.com/yungshenglu)/[docogen-html](https://github.com/toolbuddy/docoGen-WebUI) | 配合 docogen 的模組，主要從文件格式 (json,md) 轉換成 html 網頁格式 ([簡易說明](https://slides.com/kevinbird61/docogen#/)) |  [:arrow_upper_right:](https://github.com/toolbuddy/docoGen-WebUI/wiki), [demo](https://toolbuddy.github.io/docoGen-wiki/web/)
6 | [papogen](https://github.com/toolbuddy/papoGen) | 從文件格式(主要以 markdown 為主, 另外支援特定格式的 json,yaml) **快速生成** html ([簡易說明](https://toolbuddy.github.io/2017/12/27/papoGenRelease0.0.16/) |  [:arrow_upper_right:](https://toolbuddy.github.io/2017/12/18/papoGen/), [demo(markdown)](https://toolbuddy.github.io/papoGen/md/),  [demo(json,yaml)](https://toolbuddy.github.io/papoGen/),[npm package](https://www.npmjs.com/package/papogen) 

# C 

:star2: | Name | Description | 🌍
--- | --- | --- | ---
3 | [visual-ll](https://github.com/toolbuddy/visual-ll) | Using graphviz to enable visualization on linked-list implementation. | [:arrow_upper_right:](https://toolbuddy.github.io/2018/01/01/visual-ll/)

如果審核通過，我會再發 PR 給您
謝謝！

**Comment by hueitan** [comment]
Welcome pr
