### ISSUE TITLE
Track the stars automatically

### ISSUE THREAD

**Issue by ByronHsu** [hueitan/made-in-taiwan#15]
I found that the stars of projects listed on it are different to the actual one because of the time.
Hope that someone can help track the stars dynamically.

**Comment by hueitan** [comment]
Automatically is great!

**Comment by liuderchi** [comment]
We can utilize [`Shields`](https://shields.io#social) project by adding markdown image like this:

```code

![GitHub stars](https://img.shields.io/github/stars/{USER}/{REPO}.svg?style=flat-square&label=Stars)

```
Taking this project as an example (`USER=hueitan`, `REPO=made-in-taiwan`),
we got a badge like this:

![MIT-stars](https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=Stars)

And it's free! 💯 

---

Also, I have a suggestion: 

> We can add url to the shields image in a tidy way in markdown

```code
// README.md

[![MIT-stars][MIT-stars-shield]][[MIT]]

// ...

// add those in the bottom:

[MIT-stars-shield]: https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=Stars
[MIT]: https://github.com/hueitan/made-in-taiwan
```

we got a badge that _can link to repo_ like this:

[![MIT-stars][MIT-stars-shield]][MIT]

[MIT-stars-shield]: https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=Stars
[MIT]: https://github.com/hueitan/made-in-taiwan

**Comment by hueitan** [comment]
Good idea! Do you want to submit a pr for this shield?

**Comment by liuderchi** [comment]
@hueitan it's my pleasure 🎉 

Any preference to the style/wording of the badge?

IMO considering narrow space in README I would recommend this small one:

![stars](https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=🌟)

```
![stars](https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=🌟
```

**Comment by hueitan** [comment]
I prefer 

![MIT-stars][MIT-stars-shield]

[MIT-stars-shield]: https://img.shields.io/github/stars/hueitan/made-in-taiwan.svg?style=flat-square&label=Stars
[MIT]: https://github.com/hueitan/made-in-taiwan

**Comment by liuderchi** [comment]
I will make badges with url pointing to the repo

**Comment by liuderchi** [comment]
UPDATE:

Recently another new badge service -- _badgen service_ (https://badgen.net/) has launched,
as an alternative to shields.io. 

In theory it would be faster since it's built on [_Now CDN_](https://github.com/amio/badgen-service#the-badgen-story) (so need no cache control).

More badge examples: https://badgen.net/#github
