### ISSUE TITLE
remove token @ history

### ISSUE THREAD

**Issue by kewang** [hueitan/made-in-taiwan#3]
剛剛發現 `build.js` 的 `token` 有在 history 裡面，應該要 rewrite 一下 history，以防有心人亂用。

**Comment by hueitan** [comment]
被發現了 。是我 commit 上去的

但是 GitHub 有通知我，我已經馬上移除了，所以我就懶得 rewrite 了

**Comment by kewang** [comment]
有通知！？

好奇 GitHub 是不是有 validator bot 在那邊固定掃 push 上來的內容是否合法 XD

**Comment by hueitan** [comment]
我也是上傳了 token 才發現 GitHub 有檢查任何一個 Commit！

他會幫忙鎖 Token，加上發一封信到你的信箱通知，超貼心。

**Comment by hueitan** [comment]
![screen shot 2016-07-29 at 10 48 18](https://cloud.githubusercontent.com/assets/2560096/17242929/1d798374-557a-11e6-8a4f-d9ef1bb68368.png)

超貼心的吧

**Comment by kewang** [comment]
太有趣了，借轉到我的粉絲頁 XD
