### ISSUE TITLE
PHP 工具類增加 一條

### ISSUE THREAD

**Issue by suffixbig** [hueitan/made-in-taiwan#8]
180|[@suffixbig](https://github.com/suffixbig)/[**PhpDataDictionaryTool**](https://github.com/suffixbig/PhpDataDictionaryTool) |mysql數據庫字典生成工具 PHP版 (http://phpmytool.com)

**Comment by hueitan** [comment]
要不要發個 PR？

**Comment by suffixbig** [comment]
PR，我也是問人才知道是什麼 你有沒有-是不是這樣
